[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[dependencies]
good_lp = { version = "1.7", default-features = false, features = ["microlp"] }
itertools = "0.14.0"
rangemap = "1.7.0"
regex = "1.12.2"
